// Generated by https://quicktype.io
// Es una interfaz para manejar los datos del json
export interface PokemonsReponse {
  count:    number;
  next:     string;
  previous: null;
  results:  Result[];
}

export interface Result {
  name: string;
  url:  string;
}
